project:
  type: website
  output-dir: docs

website:
  title: "All About Cheng Yin"
  favicon: images/favicon.png
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: FYP Project.qmd
        text: FYP Project
      - href: hobbies.qmd
        text: Hobbies
      - href: Reflection.qmd
        text: Reflections

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
